### ISSUE TITLE
Incompatibility with sodium on minecraft 1.21

### ISSUE THREAD

**Issue by ghost** [ZeroNoRyouki/ExtremeReactors2#163] opened 2024-08-25 20:07 UTC
ER crashes in the render thread when dismantling an extreme reactor while using sodium, log provided
https://mclo.gs/73HNhV1

Playing ATM10 v 0.38, ER version is 2.4.5

Gif provided on how to reproduce
https://i.imgur.com/o2cGJ7r.gif

**Comment by IMS212** [comment] 2024-08-25 20:10
Quick technical note: This seems to be caused by ZeroCore triggering a chunk update from the server thread. This is not allowed in Sodium, and will not be allowed in the upcoming Minecraft 1.21.2 update either; so this should probably be fixed here, and not in Sodium (where it'd be removed again).

**Comment by ZeroNoRyouki** [comment] 2024-08-26 07:03
Fixed in dev

**Comment by ZeroNoRyouki** [comment] 2024-08-26 08:32
Fixed in Extreme Reactors 2.4.7 and ZeroCore 2.4.3
Have fun
Z

**Closed as completed by ZeroNoRyouki** 2024-08-26 08:32 UTC
