### ISSUE TITLE
[1.16.4] Some Turbine (visual) problems

### ISSUE THREAD

**Issue by TheSnowyChickens** [ZeroNoRyouki/ExtremeReactors2#11] opened 2020-11-27 17:52 UTC
Hello,
I found some small issues, nothing in function, but optically.

![grafik](https://user-images.githubusercontent.com/29357962/100474243-7fced100-30e0-11eb-9f49-50ac4938c10b.png)

1. as you can see in the picture, the back side from the controller is see-through 
* (edit: found this issue also at the "Turbine Passive Forge Fluid Port (Reinforced)" block)
2. 2 sides from the turbine blades are not connected to the turbine base. (in in the multiblock formed variant, they are fin in the non-multiblock)

Log: 
[2020-11-27-3.log](https://github.com/ZeroNoRyouki/ExtremeReactors2-issues/files/5609121/2020-11-27-3.log)

MC: 1.16.4
ER2: 2.0.9
ZC2: 2.0.7
Forge: 35.1.4
No Optifine or/and OptiForge
Resourcepack: yes (VanillaTweaks)

**Comment by ZeroNoRyouki** [comment] 2020-11-27 18:35
Hi there,
1) From that pic, I think I know where the problem is, I'll check it asap
2) Where the blades rendered in that way while you were assembing the Turbine (before completing the multiblock)? You have 4 blades per shaft in that pic right ?

Thanks for the report

**Comment by TheSnowyChickens** [comment] 2020-11-27 19:11
Hi,
no buggy blades during the assembly process.

![grafik](https://user-images.githubusercontent.com/29357962/100478792-95e28e80-30ec-11eb-9713-32abbc811012.png)

**Comment by ZeroNoRyouki** [comment] 2020-11-27 20:02
OK, problem n.1 solved. Trying to reproduce n.2

**Comment by ZeroNoRyouki** [comment] 2020-11-27 20:21
By any change, did you first build the turbine/rotor horizontally before going vertically?

**Comment by TheSnowyChickens** [comment] 2020-11-27 21:47
Yes, first the axle, then the blade.

**Comment by TheSnowyChickens** [comment] 2020-11-27 21:56
Found a next thing:

![grafik](https://user-images.githubusercontent.com/29357962/100486328-b23df580-3103-11eb-9b05-855100e930b5.png)

I see the particles only inside the machine or inside the glass with the spectator mode.

**Comment by ZeroNoRyouki** [comment] 2020-11-28 10:46
Thank your for the new informations. I'm aware of the particles/glass problem but it look line a non-resolved Minecraft bug (MC-161917)

**Comment by ZeroNoRyouki** [comment] 2020-11-28 11:04
> If the structure is completed and I place some blades, they are first pointed in another direction and then they hop to the final position, aka from the first picture. (for a very short duration)

Yes, there is a brief moment in with the blade could be shown in it's default orientation before being re-oriented, depending on how fast your pc/gpu is (or internet connection if you are playing on a server)
 
What I still can't reproduce is ending up with a formed rotor (in an assembled multiblock) with it's blade not oriented correctly like in your fist picture. When the multiblock if assembled the blades orientation is re-computed everytime so they should always be rendered in the correct orientation

**Comment by TheSnowyChickens** [comment] 2020-11-28 14:05
Okay, mod conflicts found.
(now installed: Fancy Menu, ER2, ZC2, Patchouli, JEI, Konkrete)
![grafik](https://user-images.githubusercontent.com/29357962/100517471-f6c0a400-318a-11eb-9841-0009926c7eaa.png)

**Comment by ZeroNoRyouki** [comment] 2020-11-29 18:02
Hi, the glitch on Controllers and other parts showing transparent is fixed in 2.0.10. Still working on the other problem.

**Comment by XCOYoshi** [comment] 2021-02-05 17:01
![image](https://user-images.githubusercontent.com/26392051/107064709-2370e780-67dc-11eb-81de-850439706908.png)
is this intendet ?

**Comment by ZeroNoRyouki** [comment] 2021-02-05 18:31
Nop, it's something I can't still reproduce. Could you zip your world and share it somewhere so I could download it and take a look?

**Comment by XCOYoshi** [comment] 2021-02-05 21:00
on it
with the modpack ?

**Comment by XCOYoshi** [comment] 2021-02-05 21:15
https://drive.google.com/file/d/1IftcMP65ZzbjdVIL5OAAB-VyNzjdeUSg/view?usp=sharing

Cords: 
![image](https://user-images.githubusercontent.com/26392051/107089911-b1aa9500-67ff-11eb-8b38-a0024d5a7339.png)

**Comment by XCOYoshi** [comment] 2021-02-05 23:02
Wen in Rotation With Create

![image](https://user-images.githubusercontent.com/26392051/107098037-9a26d880-680e-11eb-8552-7b290a0e1724.png)

**Comment by ZeroNoRyouki** [comment] 2021-02-06 10:43
> https://drive.google.com/file/d/1IftcMP65ZzbjdVIL5OAAB-VyNzjdeUSg/view?usp=sharing
> 

Thank you

**Comment by ZeroNoRyouki** [comment] 2021-02-06 10:43
> Wen in Rotation With Create

What's that?

**Comment by XCOYoshi** [comment] 2021-02-06 12:28
this is what happens when you move one of your blocks with a Create device that was a turbine shaft

**Comment by ZeroNoRyouki** [comment] 2021-02-06 13:25
They are not designed to be used in that way

**Comment by XCOYoshi** [comment] 2021-02-06 17:57
i know but all your blocks have the issu but its irelevent it just looks nice

**Comment by ZeroNoRyouki** [comment] 2021-02-06 18:06
I use blockstate to a minimum and basically only on the client so I'm not surprised to see that

**Comment by XCOYoshi** [comment] 2021-02-06 18:14
ok

**Comment by beiai** [comment] 2021-02-19 06:51
I also encountered the same problem and can reproduce the problem 100%. Here is the picture.
![20210219142800](https://user-images.githubusercontent.com/16081195/108466497-b6228380-72be-11eb-93c0-f0e51a5a2583.png)

Steps to reproduce the problem:
1. 
Minecraft: 1.16.5
forge: forge: 36.0.42
No Optifine
2. Download and replace the files in the mods zip archive
https://drive.google.com/file/d/1qffPx5dOium5nWbgBdFALH_wLuI3ITWb
3. Create a world No matter which world type.
Build a turbine no matter the size and direction.
Then you can reproduce the problem.

by the way, I found some strange things in my test.I know there are too many mod in the mods folder.
It's not that I didn't exclude some mod, but by removing any of them, the problem disappears.
I deleted them one by one, when I deleted any one of the mods, the problem went away, so eventually I had to give up doing that.

**Comment by ZeroNoRyouki** [comment] 2021-02-19 13:16
> by the way, I found some strange things in my test.I know there are too many mod in the mods folder.
> It's not that I didn't exclude some mod, but by removing any of them, the problem disappears.
> I deleted them one by one, when I deleted any one of the mods, the problem went away, so eventually I had to give up doing that.

I can reproduce it too. I've tested some mods combinations and found that:

- with all your mods : it happens, every time
- with all your mods minus FpsReducer-mc1.16.4-1.18.jar : it does NOT happen, every time
- with ER + ZC + FpsReducer-mc1.16.4-1.18.jar : it does NOT happen, every time

Can you confirm it too?

**Comment by beiai** [comment] 2021-02-19 14:50
> Can you confirm it too?
Yes, This combination already test and confirmed it.

**Comment by ZeroNoRyouki** [comment] 2021-02-20 10:26
I've found the problem and it's now fixed. An update should be out today

**Closed** 2021-02-21 10:17 UTC

**Comment by ZeroNoRyouki** [comment] 2021-02-21 10:19
Fixed in ZC 2.0.21 & ER 2.0.23

**Comment by TheSnowyChickens** [comment] 2021-02-21 16:05
Ty

**Comment by TheSnowyChickens** [comment] 2021-02-27 20:32
![grafik](https://user-images.githubusercontent.com/29357962/109399465-427a1980-7943-11eb-9027-19c70969fd1f.png)

Ahhhhhhhh, I don't have Optifine installed. :(((((
I hate this stupid render bug with glass / water and more.
